# Generated by Django 5.1.5 on 2025-02-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jewl_metals', '0002_rename_metal_id_metal_metal_unique_id_metalrate_and_more'),
        ('jewl_stones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=100, unique=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model_img', models.ImageField(upload_to='models/')),
                ('jewelry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='product_inv.jewelrytype')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='jewl_metals.metal')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='product_inv.model')),
            ],
        ),
        migrations.CreateModel(
            name='RawStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_stones', to='product_inv.model')),
                ('stone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_stones', to='jewl_stones.stonetype')),
            ],
        ),
    ]
