# Generated by Django 5.1.5 on 2025-03-08 11:35

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_inv', '0003_modelcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('no_of_pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_of_order', models.DateField(default=datetime.date.today)),
                ('est_delivery_date', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product_inv.modelcolor')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product_inv.model')),
            ],
        ),
        migrations.CreateModel(
            name='DefectiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defective_pieces', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('issue_description', models.TextField()),
                ('reported_date', models.DateField(default=datetime.date.today)),
                ('defect_image', models.ImageField(blank=True, null=True, upload_to='defective_orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defective_orders', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='RepeatedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reorder', models.DateField(default=datetime.date.today)),
                ('est_delivery_date', models.DateField()),
                ('new_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repeated_order_entry', to='order.order')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeated_orders', to='order.order')),
            ],
        ),
    ]
